In [91]:
# Reading the file
import pandas as pd

df = pd.read_csv('C:\\Users\\elhaw\\JupyterLab Projects\\Final Project\\fifa19.csv')

# Display the first few rows of the dataset
print(df.head())

# Summary of the dataset to find missing values and data types
print(df.info())

# Check for duplicate entries
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Summary statistics for numerical fields
print(df.describe())

       id          name                       full_name birth_date  age  \
0  158023      L. Messi  Lionel Andr√©s Messi Cuccittini  6/24/1987   31
1  190460    C. Eriksen    Christian  Dannemann Eriksen  2/14/1992   27
2  195864      P. Pogba                      Paul Pogba  3/15/1993   25
3  198219    L. Insigne                 Lorenzo Insigne   6/4/1991   27
4  201024  K. Koulibaly               Kalidou Koulibaly  6/20/1991   27

   height_cm  weight_kgs  positions nationality  overall_rating  ...   LWB  \
0     170.18        72.1   CF,RW,ST   Argentina              94  ...  64+2
1     154.94        76.2  CAM,RM,CM     Denmark              88  ...  71+3
2     190.50        83.9     CM,CAM      France              88  ...  76+3
3     162.56        59.0      LW,ST       Italy              88  ...  63+3
4     187.96        88.9         CB     Senegal              88  ...  73+3

    LDM   CDM   RDM   RWB    LB   LCB    CB   RCB    RB
0  61+2  61+2  61+2  64+2  59+2  48+2  48+2  48+2  59+2
1  71+3  71+3  71+3  71+3  66+3  57+3  57+3  57+3  66+3
2  77+3  77+3  77+3  76+3  74+3  72+3  72+3  72+3  74+3
3  58+3  58+3  58+3  63+3  58+3  44+3  44+3  44+3  58+3
4  77+3  77+3  77+3  73+3  76+3  85+3  85+3  85+3  76+3

[5 rows x 92 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17954 entries, 0 to 17953
Data columns (total 92 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             17954 non-null  int64
 1   name                           17954 non-null  object
 2   full_name                      17954 non-null  object
 3   birth_date                     17954 non-null  object
 4   age                            17954 non-null  int64
 5   height_cm                      17954 non-null  float64
 6   weight_kgs                     17954 non-null  float64
 7   positions                      17954 non-null  object
 8   nationality                    17954 non-null  object
 9   overall_rating                 17954 non-null  int64
 10  potential                      17954 non-null  int64
 11  value_euro                     17699 non-null  float64
 12  wage_euro                      17708 non-null  float64
 13  preferred_foot                 17954 non-null  object
 14  international_reputation(1-5)  17954 non-null  int64
 15  weak_foot(1-5)                 17954 non-null  int64
 16  skill_moves(1-5)               17954 non-null  int64
 17  work_rate                      17954 non-null  object
 18  body_type                      17954 non-null  object
 19  release_clause_euro            16117 non-null  float64
 20  club_team                      17940 non-null  object
 21  club_rating                    17940 non-null  float64
 22  club_position                  17940 non-null  object
 23  club_jersey_number             17940 non-null  float64
 24  club_join_date                 16018 non-null  object
 25  contract_end_year              17593 non-null  object
 26  national_team                  857 non-null    object
 27  national_rating                857 non-null    float64
 28  national_team_position         857 non-null    object
 29  national_jersey_number         857 non-null    float64
 30  crossing                       17954 non-null  int64
 31  finishing                      17954 non-null  int64
 32  heading_accuracy               17954 non-null  int64
 33  short_passing                  17954 non-null  int64
 34  volleys                        17954 non-null  int64
 35  dribbling                      17954 non-null  int64
 36  curve                          17954 non-null  int64
 37  freekick_accuracy              17954 non-null  int64
 38  long_passing                   17954 non-null  int64
 39  ball_control                   17954 non-null  int64
 40  acceleration                   17954 non-null  int64
 41  sprint_speed                   17954 non-null  int64
 42  agility                        17954 non-null  int64
 43  reactions                      17954 non-null  int64
 44  balance                        17954 non-null  int64
 45  shot_power                     17954 non-null  int64
 46  jumping                        17954 non-null  int64
 47  stamina                        17954 non-null  int64
 48  strength                       17954 non-null  int64
 49  long_shots                     17954 non-null  int64
 50  aggression                     17954 non-null  int64
 51  interceptions                  17954 non-null  int64
 52  positioning                    17954 non-null  int64
 53  vision                         17954 non-null  int64
 54  penalties                      17954 non-null  int64
 55  composure                      17954 non-null  int64
 56  marking                        17954 non-null  int64
 57  standing_tackle                17954 non-null  int64
 58  sliding_tackle                 17954 non-null  int64
 59  GK_diving                      17954 non-null  int64
 60  GK_handling                    17954 non-null  int64
 61  GK_kicking                     17954 non-null  int64
 62  GK_positioning                 17954 non-null  int64
 63  GK_reflexes                    17954 non-null  int64
 64  tags                           1417 non-null   object
 65  traits                         8137 non-null   object
 66  LS                             15889 non-null  object
 67  ST                             15889 non-null  object
 68  RS                             15889 non-null  object
 69  LW                             15889 non-null  object
 70  LF                             15889 non-null  object
 71  CF                             15889 non-null  object
 72  RF                             15889 non-null  object
 73  RW                             15889 non-null  object
 74  LAM                            15889 non-null  object
 75  CAM                            15889 non-null  object
 76  RAM                            15889 non-null  object
 77  LM                             15889 non-null  object
 78  LCM                            15889 non-null  object
 79  CM                             15889 non-null  object
 80  RCM                            15889 non-null  object
 81  RM                             15889 non-null  object
 82  LWB                            15889 non-null  object
 83  LDM                            15889 non-null  object
 84  CDM                            15889 non-null  object
 85  RDM                            15889 non-null  object
 86  RWB                            15889 non-null  object
 87  LB                             15889 non-null  object
 88  LCB                            15889 non-null  object
 89  CB                             15889 non-null  object
 90  RCB                            15889 non-null  object
 91  RB                             15889 non-null  object
dtypes: float64(9), int64(41), object(42)
memory usage: 12.6+ MB
None
Number of duplicate rows: 0
                  id           age     height_cm    weight_kgs  \
count   17954.000000  17954.000000  17954.000000  17954.000000
mean   215411.087780     25.565445    174.946921     75.301047
std     29758.387106      4.705708     14.029449      7.083684
min        16.000000     17.000000    152.400000     49.900000
25%    201117.250000     22.000000    154.940000     69.900000
50%    222919.000000     25.000000    175.260000     74.800000
75%    237613.500000     29.000000    185.420000     79.800000
max    247607.000000     46.000000    205.740000    110.200000

       overall_rating     potential    value_euro      wage_euro  \
count    17954.000000  17954.000000  1.769900e+04   17708.000000
mean        66.240169     71.430935  2.479280e+06    9902.134628
std          6.963730      6.131339  5.687014e+06   21995.593750
min         47.000000     48.000000  1.000000e+04    1000.000000
25%         62.000000     67.000000  3.250000e+05    1000.000000
50%         66.000000     71.000000  7.000000e+05    3000.000000
75%         71.000000     75.000000  2.100000e+06    9000.000000
max         94.000000     95.000000  1.105000e+08  565000.000000

       international_reputation(1-5)  weak_foot(1-5)  ...     penalties  \
count                   17954.000000    17954.000000  ...  17954.000000
mean                        1.111674        2.945695  ...     48.357302
std                         0.392168        0.663691  ...     15.810844
min                         1.000000        1.000000  ...      5.000000
25%                         1.000000        3.000000  ...     38.000000
50%                         1.000000        3.000000  ...     49.000000
75%                         1.000000        3.000000  ...     60.000000
max                         5.000000        5.000000  ...     92.000000

          composure       marking  standing_tackle  sliding_tackle  \
count  17954.000000  17954.000000     17954.000000    17954.000000
mean      58.680183     47.162861        47.733040       45.705915
std       11.625541     20.037346        21.674973       21.285812
min       12.000000      3.000000         2.000000        3.000000
25%       51.000000     30.000000        27.000000       24.000000
50%       60.000000     52.500000        55.000000       52.000000
75%       67.000000     64.000000        66.000000       64.000000
max       96.000000     94.000000        93.000000       90.000000

          GK_diving   GK_handling    GK_kicking  GK_positioning   GK_reflexes
count  17954.000000  17954.000000  17954.000000    17954.000000  17954.000000
mean      16.784449     16.556199     16.388660       16.541049     16.874067
std       17.893895     17.108234     16.701447       17.231495     18.182943
min        1.000000      1.000000      1.000000        1.000000      1.000000
25%        8.000000      8.000000      8.000000        8.000000      8.000000
50%       11.000000     11.000000     11.000000       11.000000     11.000000
75%       14.000000     14.000000     14.000000       14.000000     14.000000
max       90.000000     92.000000     92.000000       90.000000     94.000000

[8 rows x 50 columns]

In [93]:
# Check for columns with high percentage of missing values
missing_data = df.isnull().mean() * 100
columns_with_missing_data = missing_data[missing_data > 0].sort_values(ascending=False)
print(columns_with_missing_data)

# Drop columns with more than 50% missing values
df = df.drop(columns=columns_with_missing_data[columns_with_missing_data > 50].index)

# Fill missing values in numeric columns with the median
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    df[col] = df[col].fillna(df[col].median())

# Handle categorical columns by replacing missing values with the mode
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

national_team_position    95.226690
national_team             95.226690
national_rating           95.226690
national_jersey_number    95.226690
tags                      92.107608
traits                    54.678623
LM                        11.501615
LCM                       11.501615
CM                        11.501615
RCM                       11.501615
RM                        11.501615
LWB                       11.501615
LDM                       11.501615
CF                        11.501615
CAM                       11.501615
CDM                       11.501615
RDM                       11.501615
RWB                       11.501615
LB                        11.501615
LCB                       11.501615
CB                        11.501615
RCB                       11.501615
RAM                       11.501615
RB                        11.501615
LAM                       11.501615
LW                        11.501615
RW                        11.501615
ST                        11.501615
RS                        11.501615
LS                        11.501615
LF                        11.501615
RF                        11.501615
club_join_date            10.783112
release_clause_euro       10.231703
contract_end_year          2.010694
value_euro                 1.420296
wage_euro                  1.370168
club_jersey_number         0.077977
club_position              0.077977
club_rating                0.077977
club_team                  0.077977
dtype: float64

In [95]:
# Convert date columns to datetime format
df['birth_date'] = pd.to_datetime(df['birth_date'])

# Ensure correct data types
df['club_jersey_number'] = df['club_jersey_number'].astype(float)

df['BMI'] = df['weight_kgs'] / (df['height_cm'] / 100) ** 2

# Display the first few rows of the dataset
print(df.head())

# Summary of the dataset to find missing values and data types
print(df.info())

# Check for duplicate entries
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Summary statistics for numerical fields
print(df.describe())

       id          name                       full_name birth_date  age  \
0  158023      L. Messi  Lionel Andr√©s Messi Cuccittini 1987-06-24   31
1  190460    C. Eriksen    Christian  Dannemann Eriksen 1992-02-14   27
2  195864      P. Pogba                      Paul Pogba 1993-03-15   25
3  198219    L. Insigne                 Lorenzo Insigne 1991-06-04   27
4  201024  K. Koulibaly               Kalidou Koulibaly 1991-06-20   27

   height_cm  weight_kgs  positions nationality  overall_rating  ...   LDM  \
0     170.18        72.1   CF,RW,ST   Argentina              94  ...  61+2
1     154.94        76.2  CAM,RM,CM     Denmark              88  ...  71+3
2     190.50        83.9     CM,CAM      France              88  ...  77+3
3     162.56        59.0      LW,ST       Italy              88  ...  58+3
4     187.96        88.9         CB     Senegal              88  ...  77+3

    CDM   RDM   RWB    LB   LCB    CB   RCB    RB        BMI
0  61+2  61+2  64+2  59+2  48+2  48+2  48+2  59+2  24.895349
1  71+3  71+3  71+3  66+3  57+3  57+3  57+3  66+3  31.741531
2  77+3  77+3  76+3  74+3  72+3  72+3  72+3  74+3  23.119157
3  58+3  58+3  63+3  58+3  44+3  44+3  44+3  58+3  22.326705
4  77+3  77+3  73+3  76+3  85+3  85+3  85+3  76+3  25.163491

[5 rows x 87 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17954 entries, 0 to 17953
Data columns (total 87 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             17954 non-null  int64
 1   name                           17954 non-null  object
 2   full_name                      17954 non-null  object
 3   birth_date                     17954 non-null  datetime64[ns]
 4   age                            17954 non-null  int64
 5   height_cm                      17954 non-null  float64
 6   weight_kgs                     17954 non-null  float64
 7   positions                      17954 non-null  object
 8   nationality                    17954 non-null  object
 9   overall_rating                 17954 non-null  int64
 10  potential                      17954 non-null  int64
 11  value_euro                     17954 non-null  float64
 12  wage_euro                      17954 non-null  float64
 13  preferred_foot                 17954 non-null  object
 14  international_reputation(1-5)  17954 non-null  int64
 15  weak_foot(1-5)                 17954 non-null  int64
 16  skill_moves(1-5)               17954 non-null  int64
 17  work_rate                      17954 non-null  object
 18  body_type                      17954 non-null  object
 19  release_clause_euro            17954 non-null  float64
 20  club_team                      17954 non-null  object
 21  club_rating                    17954 non-null  float64
 22  club_position                  17954 non-null  object
 23  club_jersey_number             17954 non-null  float64
 24  club_join_date                 17954 non-null  object
 25  contract_end_year              17954 non-null  object
 26  crossing                       17954 non-null  int64
 27  finishing                      17954 non-null  int64
 28  heading_accuracy               17954 non-null  int64
 29  short_passing                  17954 non-null  int64
 30  volleys                        17954 non-null  int64
 31  dribbling                      17954 non-null  int64
 32  curve                          17954 non-null  int64
 33  freekick_accuracy              17954 non-null  int64
 34  long_passing                   17954 non-null  int64
 35  ball_control                   17954 non-null  int64
 36  acceleration                   17954 non-null  int64
 37  sprint_speed                   17954 non-null  int64
 38  agility                        17954 non-null  int64
 39  reactions                      17954 non-null  int64
 40  balance                        17954 non-null  int64
 41  shot_power                     17954 non-null  int64
 42  jumping                        17954 non-null  int64
 43  stamina                        17954 non-null  int64
 44  strength                       17954 non-null  int64
 45  long_shots                     17954 non-null  int64
 46  aggression                     17954 non-null  int64
 47  interceptions                  17954 non-null  int64
 48  positioning                    17954 non-null  int64
 49  vision                         17954 non-null  int64
 50  penalties                      17954 non-null  int64
 51  composure                      17954 non-null  int64
 52  marking                        17954 non-null  int64
 53  standing_tackle                17954 non-null  int64
 54  sliding_tackle                 17954 non-null  int64
 55  GK_diving                      17954 non-null  int64
 56  GK_handling                    17954 non-null  int64
 57  GK_kicking                     17954 non-null  int64
 58  GK_positioning                 17954 non-null  int64
 59  GK_reflexes                    17954 non-null  int64
 60  LS                             17954 non-null  object
 61  ST                             17954 non-null  object
 62  RS                             17954 non-null  object
 63  LW                             17954 non-null  object
 64  LF                             17954 non-null  object
 65  CF                             17954 non-null  object
 66  RF                             17954 non-null  object
 67  RW                             17954 non-null  object
 68  LAM                            17954 non-null  object
 69  CAM                            17954 non-null  object
 70  RAM                            17954 non-null  object
 71  LM                             17954 non-null  object
 72  LCM                            17954 non-null  object
 73  CM                             17954 non-null  object
 74  RCM                            17954 non-null  object
 75  RM                             17954 non-null  object
 76  LWB                            17954 non-null  object
 77  LDM                            17954 non-null  object
 78  CDM                            17954 non-null  object
 79  RDM                            17954 non-null  object
 80  RWB                            17954 non-null  object
 81  LB                             17954 non-null  object
 82  LCB                            17954 non-null  object
 83  CB                             17954 non-null  object
 84  RCB                            17954 non-null  object
 85  RB                             17954 non-null  object
 86  BMI                            17954 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(41), object(37)
memory usage: 11.9+ MB
None
Number of duplicate rows: 0
                  id                     birth_date           age  \
count   17954.000000                          17954  17954.000000
mean   215411.087780  1993-02-17 21:53:21.381307648     25.565445
min        16.000000            1973-02-01 00:00:00     17.000000
25%    201117.250000            1989-11-02 00:00:00     22.000000
50%    222919.000000            1993-06-30 00:00:00     25.000000
75%    237613.500000            1996-12-30 00:00:00     29.000000
max    247607.000000            2002-02-26 00:00:00     46.000000
std     29758.387106                            NaN      4.705708

          height_cm    weight_kgs  overall_rating     potential    value_euro  \
count  17954.000000  17954.000000    17954.000000  17954.000000  1.795400e+04
mean     174.946921     75.301047       66.240169     71.430935  2.454009e+06
min      152.400000     49.900000       47.000000     48.000000  1.000000e+04
25%      154.940000     69.900000       62.000000     67.000000  3.250000e+05
50%      175.260000     74.800000       66.000000     71.000000  7.000000e+05
75%      185.420000     79.800000       71.000000     75.000000  2.000000e+06
max      205.740000    110.200000       94.000000     95.000000  1.105000e+08
std       14.029449      7.083684        6.963730      6.131339  5.650405e+06

           wage_euro  international_reputation(1-5)  ...     composure  \
count   17954.000000                   17954.000000  ...  17954.000000
mean     9807.563774                       1.111674  ...     58.680183
min      1000.000000                       1.000000  ...     12.000000
25%      1000.000000                       1.000000  ...     51.000000
50%      3000.000000                       1.000000  ...     60.000000
75%      9000.000000                       1.000000  ...     67.000000
max    565000.000000                       5.000000  ...     96.000000
std     21859.109090                       0.392168  ...     11.625541

            marking  standing_tackle  sliding_tackle     GK_diving  \
count  17954.000000     17954.000000    17954.000000  17954.000000
mean      47.162861        47.733040       45.705915     16.784449
min        3.000000         2.000000        3.000000      1.000000
25%       30.000000        27.000000       24.000000      8.000000
50%       52.500000        55.000000       52.000000     11.000000
75%       64.000000        66.000000       64.000000     14.000000
max       94.000000        93.000000       90.000000     90.000000
std       20.037346        21.674973       21.285812     17.893895

        GK_handling    GK_kicking  GK_positioning   GK_reflexes           BMI
count  17954.000000  17954.000000    17954.000000  17954.000000  17954.000000
mean      16.556199     16.388660       16.541049     16.874067     24.933142
min        1.000000      1.000000        1.000000      1.000000     16.954928
25%        8.000000      8.000000        8.000000      8.000000     22.365014
50%       11.000000     11.000000       11.000000     11.000000     23.473057
75%       14.000000     14.000000       14.000000     14.000000     27.034453
max       92.000000     92.000000       90.000000     94.000000     47.447317
std       17.108234     16.701447       17.231495     18.182943      3.868855

[8 rows x 50 columns]